/// Problem 2 - Even Fibonacci Numbers
///
/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
///
/// Author: Vili Lähtevänoja

let problem002 =
    let rec fibonacci n =
        if (n < 2)
            then 1
        else fibonacci(n - 2) + fibonacci (n - 1)
    let result =
        Seq.sumBy (fun n -> if n % 2 = 0 then n else 0) (Seq.takeWhile (fun n -> n < 4000000) (Seq.initInfinite (fun n -> fibonacci n)))
    result
    ;;